#!/bin/bash

# Find contracts that emit events from their __constructor functions.
# Uses callgraph data (generated by wasm-call-graph --leaves-only) to check
# if __constructor transitively calls contract_event.
# Includes event names and function names from the contract spec.

echo "wasm_hash,events,functions"

for file in callgraph/*.txt; do
    if [ -f "$file" ] && grep -q "^__constructor,contract_event$" "$file"; then
        hash=$(basename "$file" .txt)
        spec="specs/${hash}.json"
        if [ -f "$spec" ]; then
            events=$(jq -r '[.[] | select(.event_v0) | .event_v0.name] | join(",")' "$spec" 2>/dev/null)
            fns=$(jq -r '[.[] | select(.function_v0) | .function_v0.name] | join(",")' "$spec" 2>/dev/null)
        else
            events=""
            fns=""
        fi
        echo "${hash},\"${events}\",\"${fns}\""
    fi
done
